clean:
	rm -rf _site/ 
	rm -rf .sass-cache/ 
	rm -rf .jekyll-cache/

install:
	bundle install

build:
	bundle exec jekyll build

run:
	bundle exec jekyll serve

lint:
	bundle exec rubocop

lintfix:
	bundle exec rubocop -a