language: ruby
cache: bundler

before_install:
  - gem update --system
  - gem install bundler

install:
  - make install

script:
  - make build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _site
  target-branch: gh-pages
  on:
    branch: main
