title: "Kids: a Jekyll theme"
lang: "en"
repository:
  url: https://github.com/dirtyhenry/kids
  name: dirtyhenry/kids
email: your-email@example.com
port: 4001
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: /kids
show_excerpts: true
markdown: CommonMark
permalink: /:title/

commonmark:
  options:
    # Use smart punctuation (curly quotes, etc.).
    - SMART
    # Parse footnotes.
    - FOOTNOTES
    # Allow raw HTML (required for jekyll-assets to work properly).
    - UNSAFE
  extensions:
    - strikethrough
    - autolink
    - table

jekyll-archives:
  enabled: ["categories", "tags"]
  layout: archive
  slug_mode: latin
  permalinks:
    tag: "/tag/:name/"
    category: "/category/:name/"

kids:
  # A boolean indicating if the site contains an Apple touch icon file
  apple_touch_icon: false
  # The path to the page using the archives template
  archives_path: "archives.html"
  # The maximal number of posts featured on the home
  home_posts: 5
  # A boolean indicating if the site contains a `site.webmanifest` file
  webmanifest: false
  header_pages:
    - about.md
    - header.md
  footer_pages:
    - archives.md
    - footer.md
    - inspiration.md

# Build settings
theme: kids

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - kids.gemspec
  - Makefile
  - LICENSE
